name: Proxy scraper 2h

on:
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours
  push:
    paths:
      - script.py

jobs:
  update_script: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install discord-webhook
          pip install pytz
          pip install PyGithub
          cd /home/runner/work/cskphpbalance/cskphpbalance
          ls

      - name: Run Script
        run: python script.py
        env:
          GITHUB_TOKEN: ${{ secrets.GGK_TKK }}
